name: CI

on: push
permissions:
 statuses: write
 checks: write
 contents: read
 pull-requests: write

jobs:
  test:
    name: Run tests and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

