name: CI

on: push 

permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    name: Run tests and lint
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v6.0.1

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
